/*
 * AuditTablePanel.java
 *
 * Created on February 1, 2007, 3:10 PM
 */

package com.bluecubs.xinco.client.panel;

import com.bluecubs.xinco.client.XincoExplorer;
import java.util.ResourceBundle;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  javydreamercsw
 */
public class AuditTablePanel extends javax.swing.JPanel {
    private XincoExplorer explorer;
    /** Creates new form AuditTablePanel */
    public AuditTablePanel(XincoExplorer e) {
        this.explorer=e;
        ResourceBundle xerb=this.explorer.getResourceBundle();
        initComponents();
        String[] cn = {xerb.getString("window.repository.table.attribute"),xerb.getString("window.repository.table.details")};
            DefaultTableModel dtm = new DefaultTableModel(cn, 0) { 
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            this.auditTable.setModel(dtm);
            this.auditTable.setColumnSelectionAllowed(false);
            this.auditTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.auditTable.setRowSelectionAllowed(false);
            this.auditTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            this.auditTable.setCellSelectionEnabled(false);
            this.auditTable.setEnabled(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        auditTable = new javax.swing.JTable();

        jScrollPane1.setName("auditTable");
        auditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(auditTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auditTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
