/**
 *Copyright 2007 blueCubs.com
 *
 *Licensed under the Apache License, Version 2.0 (the "License");
 *you may not use this file except in compliance with the License.
 *You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *Unless required by applicable law or agreed to in writing, software
 *distributed under the License is distributed on an "AS IS" BASIS,
 *WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *See the License for the specific language governing permissions and
 *limitations under the License.
 *
 *************************************************************
 * This project supports the blueCubs vision of giving back
 * to the community in exchange for free software!
 * More information on: http://www.bluecubs.org
 *************************************************************
 *
 * Name:            AuditTablePanel
 *
 * Description:     AuditTable Panel
 *
 * Original Author: Javier A. Ortiz
 * Date:            2007
 *
 * Modifications:
 *
 * Who?             When?             What?
 * 
 *
 *************************************************************
 * AuditTablePanel.java
 *
 * Created on February 1, 2007, 3:10 PM
 */

package com.bluecubs.xinco.client.panel;

import com.bluecubs.xinco.client.XincoExplorer;
import java.util.ResourceBundle;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  javydreamercsw
 */
public class AuditTablePanel extends javax.swing.JPanel {
    private XincoExplorer explorer;
    /** Creates new form AuditTablePanel */
    public AuditTablePanel(XincoExplorer e) {
        this.explorer=e;
        ResourceBundle xerb=this.explorer.getResourceBundle();
        initComponents();
        String[] cn = {xerb.getString("window.repository.table.attribute"),xerb.getString("window.repository.table.details")};
            DefaultTableModel dtm = new DefaultTableModel(cn, 0) { 
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            this.auditTable.setModel(dtm);
            this.auditTable.setColumnSelectionAllowed(false);
            this.auditTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            this.auditTable.setRowSelectionAllowed(false);
            this.auditTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            this.auditTable.setCellSelectionEnabled(false);
            this.auditTable.setEnabled(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        auditTable = new javax.swing.JTable();

        jScrollPane1.setName("auditTable");
        auditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(auditTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auditTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
