/**
 *Copyright 2007 blueCubs.com
 *
 *Licensed under the Apache License, Version 2.0 (the "License");
 *you may not use this file except in compliance with the License.
 *You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *Unless required by applicable law or agreed to in writing, software
 *distributed under the License is distributed on an "AS IS" BASIS,
 *WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *See the License for the specific language governing permissions and
 *limitations under the License.
 *
 *************************************************************
 * This project supports the blueCubs vision of giving back
 * to the community in exchange for free software!
 * More information on: http://www.bluecubs.org
 *************************************************************
 *
 * Name:            Repository
 *
 * Description:     Repository
 *
 * Original Author: Javier A. Ortiz
 * Date:            2007
 *
 * Modifications:
 *
 * Who?             When?             What?
 * 
 *
 *************************************************************
 * Repository.java
 *
 * Created on February 1, 2007, 1:55 PM
 */

package com.bluecubs.xinco.client.panel;

import com.bluecubs.xinco.client.XincoExplorer;
import java.awt.GridLayout;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author  javydreamercsw
 */
public class Repository extends javax.swing.JPanel {
    private XincoExplorer explorer;
    /** Creates new form Repository */
    public Repository(XincoExplorer e) {
        this.explorer=e;
        ResourceBundle xerb=this.explorer.getResourceBundle();
        initComponents();
        JTabbedPane tabbedPane = new JTabbedPane();
        JComponent panel1 = makeTextPanel("Panel #1");
        tabbedPane.addTab(xerb.getString("window.tab.title.metadata"),
                createImageIcon("blueCubsIconSmall.gif"),
                this.explorer.getJScrollPaneRepositoryTable(),
                xerb.getString("window.tab.tooltip.metadata"));
        tabbedPane.addTab(xerb.getString("window.tab.title.audit"), 
                createImageIcon("blueCubsIconSmall.gif"), new AuditTablePanel(this.explorer),
                xerb.getString("window.tab.tooltip.audit"));
        this.SplitPane.setLeftComponent(this.explorer.getJScrollPaneRepositoryTree());
        this.SplitPane.setRightComponent(tabbedPane);
        this.SplitPane.setDividerLocation(2.0/3.0);
        this.SplitPane.setResizeWeight(1);
        this.SplitPane.setContinuousLayout(true);
        setVisible(true);
    }
    
    protected JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(false);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout(1, 1));
        panel.add(filler);
        return panel;
    }
    
    /** Returns an ImageIcon, or null if the path was invalid. */
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = XincoExplorer.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        SplitPane = new javax.swing.JSplitPane();

        SplitPane.setDividerLocation(300);
        SplitPane.setAutoscrolls(true);
        SplitPane.setContinuousLayout(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    // End of variables declaration//GEN-END:variables
    
}
