/*
 * RepositoryPanel.java
 *
 * Created on February 15, 2007, 8:29 AM
 */

package com.bluecubs.xinco.client.pane;

import com.bluecubs.xinco.client.XincoExplorer;
import java.util.ResourceBundle;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JTabbedPane;

/**
 *
 * @author  Javier A. Ortiz
 */
public class RepositoryPanel extends java.awt.Panel {
    private XincoExplorer explorer;
    private ResourceBundle rb;
    /** Creates new form RepositoryPanel */
    public RepositoryPanel(XincoExplorer e) {
        this.explorer=e;
        this.rb=this.explorer.getResourceBundle();
        initComponents();
        this.RepositorySplitPane.setLeftComponent(this.explorer.getJScrollPaneRepositoryTree());
        this.RepositorySplitPane.setDividerLocation(2.0/3.0);
        JTabbedPane tabbedPane = new JTabbedPane();
        ImageIcon icon = createImageIcon("blueCubsIcon16x16.GIF");
        JComponent tablePanel=this.explorer.getJScrollPaneRepositoryTable();
        tabbedPane.addTab(rb.getString("window.audit.tablepanelabel"), icon, tablePanel);
        tabbedPane.addTab(rb.getString("window.audit.auditpanelabel"), icon, 
                new XincoAuditPanel(this.explorer));
        this.RepositorySplitPane.setRightComponent(tabbedPane);
    }
    
        /** Returns an ImageIcon, or null if the path was invalid. */
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = XincoExplorer.class.getResource(path);

        if (imgURL != null) {
            return new ImageIcon(imgURL);
        }
        System.err.println("Couldn\'t find file: " + path);
        return null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        RepositorySplitPane = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        RepositorySplitPane.setDividerLocation(300);
        RepositorySplitPane.setResizeWeight(1.0);
        RepositorySplitPane.setAutoscrolls(true);
        RepositorySplitPane.setContinuousLayout(true);
        RepositorySplitPane.setOneTouchExpandable(true);
        jTabbedPane1.setAutoscrolls(true);
        RepositorySplitPane.setRightComponent(jTabbedPane1);

        add(RepositorySplitPane, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane RepositorySplitPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
