/*
 * InformationFrame.java
 *
 * Created on September 25, 2006, 6:57 PM
 */

package com.bluecubs.xinco.client.frames;

import com.bluecubs.xinco.client.XincoExplorer;

/**
 *
 * @author  ortizbj
 */
public class InformationFrame extends javax.swing.JInternalFrame {
    private XincoExplorer explorer=null;
    /** Creates new form InformationFrame */
    private InformationFrame(XincoExplorer explorer) {
        initComponents();
        this.explorer=explorer;
        setTitle(explorer.getResourceBundle().getString("window.information"));
    }
    
    private javax.swing.JTextArea getTextArea(){
        return this.Text;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();

        setVisible(true);
        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Text;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
